version: '2'

services:

  eureka-server:
    build: ../netflixbluemix-core/eurekaserver/docker
    image: dev/spring-eureka-server
    expose:
     - "8080"
    mem_limit: 0

  eureka-server-dr:
    build: ../netflixbluemix-core/eurekaserverdr/docker
    image: dev/spring-eureka-server-dr
    links:
      - eureka-server:eureka-server
    expose:
     - "8080"
    mem_limit: 0

  zuul-proxy:
    build: ../netflixbluemix-core/zuulproxy/docker
    image: dev/spring-zuul-proxy
    links:
      - eureka-server:eureka-server
      - eureka-server-dr:eureka-server-dr
    expose:
     - "8080"
    mem_limit: 0

  hystrix-dashboard:
    build: ../netflixbluemix-core/hystrix-dashboard/docker
    image: dev/spring-hystrix-dashboard
    links:
      - eureka-server:eureka-server
      - eureka-server-dr:eureka-server-dr
    ports:
     - "8080:8080"
    mem_limit: 0

  nginx:
    build: ../netflixbluemix-core/nginx
    image: dev/noss-nginx
    links:
      - eureka-server:eureka-server
      - eureka-server-dr:eureka-server-dr
      - zuul-proxy:zuul-proxy
    ports:
      - "80:80"
    mem_limit: 0

  db2-hello-service:
   build: ../netflixbluemix-db2/db2microservice/docker
   image: dev/db2-hello-service
   links:
     - eureka-server:eureka-server
     - eureka-server-dr:eureka-server-dr
     - nginx:nginx
   expose:
     - "8080"
   mem_limit: 0
   environment:
     - spring.datasource.url=jdbc:db2://awh-yp-small02.services.dal.bluemix.net:50000/BLUDB:currentSchema=DB2INST1;
     - spring.datasource.username=dash111377
     - spring.datasource.password=o5nkbAK809xx

  mysql-hello-service:
   build: ../netflixbluemix-mysql/microservice/docker
   image: dev/mysql-hello-service
   links:
     - eureka-server:eureka-server
     - eureka-server-dr:eureka-server-dr
     - nginx:nginx
   expose:
     - "8080"
   mem_limit: 0

  mq-hello-service:
   build: ../netflixbluemix-mq/mqmicroservice/docker
   image: dev/mq-hello-service
   links:
     - eureka-server:eureka-server
     - eureka-server-dr:eureka-server-dr
     - nginx:nginx
   expose:
     - "8080"
   mem_limit: 0

  elasticsearch-server:
    image: elasticsearch:1.7.3
    links:
     - nginx:nginx
    expose:
     - "9200"
     - "9300"
    mem_limit: 0

  elasticsearch-service:
   build: ../netflixbluemix-elasticsearch/elasticsearchservice/docker
   links:
     - eureka-server:eureka-server
     - eureka-server-dr:eureka-server-dr
     - elasticsearch-server:elasticsearch-server
     - nginx:nginx
   expose:
     - "8080"
   mem_limit: 0
