server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0