eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka-server:8080/eureka/
       # for Bluemix Deployment
       # defaultZone: http://134.168.16.210/eureka/v2/,http://172.31.0.26:8080/eureka/v2/
      
info:
  component: Zuul Proxy Server Bluemix

# Spring properties
spring:
  application:
     name: zuul-proxy

cloud:
  conablefig:
    failFast: true
    discovery:
      end: true

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    hello: DEBUG