eureka:
  instance:
     preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/
      #defaultZone: http://134.168.16.210/eureka/v2/,http://172.31.0.26:8080/eureka/v2/

# Spring properties
spring:
  application:
     name: mq-hello-service
     
     
  rabbitmq:
     host: white-swan.rmq.cloudamqp.com
     username: ethewlzu
     password: XE7I5y5A9fk4XsdG0LvzL6PxynFY970a
     virtualHost: ethewlzu

# Server configuration
server:
  context-path: /app/mq